### ISSUE TITLE
Use of "Interface" in the layer boxes

### ISSUE THREAD

**Issue by SamCooper** [SamCooper/REF_MODEL_RIDS#1]
Looking at Figure 2-3 the box that represents the adaption of the service API to the MAL API is called an interface. It is not really an interface, it represents an interface to the layer above and uses an interface from below.

These boxes should be renamed, and any section in the document following should be updated to reflect this name change.

**Comment by S-Gaertner** [comment]
What about "Consumer/Provider Interface Adapter" with an explanation in the text along the line "... adapts the MAL API to the consumed/provided service interface"?

**Comment by SamCooper** [comment]
In the GB I am referring to this layer as the "Service Adaption Layer". So it could be "Consumer/Provider Service Adapter"?

**Comment by S-Gaertner** [comment]
Sounds good to me!

Btw, do you have the image sources available? The Word file only contains raster images.

**Comment by SamCooper** [comment]
Its an Enterprise Architect file, do you have that application?

**Comment by S-Gaertner** [comment]
Yes, but only version 10.

**Comment by SamCooper** [comment]
I use version 9.3 so it might work.

Alternatively you can just leave the original diagram in and add a comment to the file saying what needs to change and I can make the changes afterwards (as I need them for the green book anyway).

**Comment by S-Gaertner** [comment]
Whatever suits you best. For the moment I'll put comments in the file and we can talk about it in Berlin.

**Comment by SamCooper** [comment]
Done
